name: PR Approvals Github Action
on:
  pull_request_review:
    types: [edited, submitted]
jobs:
  run:
    name: Test if works
    runs-on: [ubuntu-latest]
    if: startsWith(github.event.pull_request.head.ref, 'pre-release') == true
    steps:
      - name: Echo
        run: |
          echo ${{ github.event.pull_request.head.ref }}

